name = "Latlib"
uuid = "c4002ea4-6ce3-4785-97ba-a9d3015475cb"
authors = ["Alex Wietek <awietek@pks.mpg.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
